- hosts: localhost
  connection: local
  vars :
    # var_user_id: "{{user_id}}"
    var_rg: "dojoazure-{{user_id}}-ex02"
    var_location: "francecentral"
    var_vnet_name: "vnet-{{user_id}}-ex02"
    var_subnet_vm_name : "vms"
    var_nsg_vm_name: "nsg-{{user_id}}-ex02-vms-nsg"
    # var_bastion_name : "bastion-{{user_id}}-ex02"
    # var_subnet_bastion_name: "AzureBastionSubnet"
    var_vm_name: "vm-{{user_id}}-ex02"
    var_tags: 
        project: dojoazure
        user: us01
        exercice: ex02
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{var_rg}}"
        location: "{{var_location}}"
      register: rg

    - debug:
        var: rg

    - name : Create Vnet
      azure_rm_virtualnetwork:
        name: "{{var_vnet_name}}"
        resource_group: "{{var_rg}}"
        address_prefixes_cidr: 
            - "10.0.0.0/23"
        tags: "{{var_tags}}"
      register: vnet

    - debug:
        var: vnet

    - name : Create NSG for VMs subnet
      azure_rm_securitygroup:
        name: "{{var_nsg_vm_name}}"
        resource_group: "{{var_rg}}"
        purge_rules: yes
        rules:
            - name: AllowRdp
              protocol: Tcp
              source_address_prefix:
                - 164.138.242.81
                - 164.138.240.21 
              destination_port_range: 3389
              access: Allow
              priority: 100
              direction: Inbound
      register: nsg_vms

    - debug:
        var: nsg_vms

    - name : Create VMs subnet
      azure_rm_subnet:
        name: "{{var_subnet_vm_name}}"
        resource_group: "{{var_rg}}"
        virtual_network_name: "{{var_vnet_name}}"
        address_prefix_cidr: "10.0.0.0/24"
        security_group: "{{var_nsg_vm_name}}"
      register : subnet_vm

    - debug:
        var: subnet_vm

    - name : Create VM Windows
      azure_rm_virtualmachine:
        name: "{{var_vm_name}}"
        resource_group: "{{var_rg}}"
        admin_username: "admincheops"
        admin_password: "{{admin_password}}"
        managed_disk_type: Standard_LRS
        virtual_network_name: "{{var_vnet_name}}"
        subnet_name: "{{var_subnet_vm_name}}"
        os_type: "Windows"
        image:
            offer: "WindowsServer"
            publisher: "MicrosoftWindowsServer"
            sku: "2019-Datacenter"
            version: "latest"
        vm_size: "Standard_DS1_v2"
        # public_ip_allocation_method: "Disabled"
        open_ports: ""
      register : vm_windows

    - debug:
        var: vm_windows